#!/bin/bash

basedir=`dirname $0`
cd $basedir
. ../../setup-env.sh
set -x

INCLUDES="-I /home/maaz/Desktop/Research/rake/halide/distrib/include -I /home/maaz/Desktop/Research/rake/halide/distrib/tools"
HL_LIBS="/home/maaz/Desktop/Research/rake/halide/distrib/lib/libHalide.a"

#############################################################################
cat <<EOT
=== Build Host/Hexagon executable for simulation ===
EOT

rm -fr ./bin
mkdir -p bin/host

${CXX} -std=c++11 $INCLUDES  -g -fno-rtti blur.cpp $HALIDE_ROOT/tools/GenGen.cpp -g $HL_LIBS -o bin/blur.generator -ldl -lpthread -lz -ldl -lpthread -lz -lz -lrt -ldl -ltinfo -lpthread
export LD_LIBRARY_PATH=$HALIDE_ROOT/lib/host:${HL_HEXAGON_TOOLS_SIM}/lib/iss/:.

bin/blur.generator -g halide_blur -o ./bin/host target=host-hvx_128
${CXX} -fopenmp -std=c++11 $INCLUDES -I ./bin/host -O3 \
		test.cpp \
		./bin/host/halide_blur.a \
		-o bin/host/test \
		-Wall -lpthread -ldl -lm 
./bin/host/test #1920 1080 ../../testvectors/football1920x1080.bin

rm pmu_stats.txt