#lang rosette/safe

(require
  (only-in racket/base error)
  rosette/lib/destruct
  rake/x86/ast/types
)

(provide (prefix-out x86: (all-defined-out)))

(define (max-unique-inputs expr)
  (destruct expr

    [(x86:??load _ _ _ _ _) 1]
    [(x86:??shuffle _ _ _) 1]
    [(x86:??swizzle _ _ _ _ _) 1]
    [(x86:reinterpret v) (max-unique-inputs v)]

    [(x86:resize a) (max-unique-inputs a)]
    [(x86:vbroadcasti128 a) (max-unique-inputs a)]
    [(x86:vpabsb a) (max-unique-inputs a)]
    [(x86:vpabsd a) (max-unique-inputs a)]
    [(x86:vpabsw a) (max-unique-inputs a)]
    [(x86:vpackssdw a b)(+)]
    [(x86:vpacksswb a b)(+)]
    [(x86:vpackusdw a b)(+)]
    [(x86:vpackuswb a b)(+)]
    [(x86:vpaddb a b)(+)]
    [(x86:vpaddd a b)(+)]
    [(x86:vpaddq a b)(+)]
    [(x86:vpaddsb a b)(+)]
    [(x86:vpaddsw a b)(+)]
    [(x86:vpaddusb a b)(+)]
    [(x86:vpaddusw a b)(+)]
    [(x86:vpaddw a b)(+)]
    [(x86:vpalignr a b imm8)(+)]
    [(x86:vpand a b)(+)]
    [(x86:vpandn a) (max-unique-inputs a)]
    [(x86:vpavgb a b)(+)]
    [(x86:vpavgw a b)(+)]
    [(x86:vpblendd a b imm8)(+)]
    [(x86:vpblendd_128 a b imm8)(+)]
    [(x86:vpblendvb a b c)(+)]
    [(x86:vpblendw a b imm8)(+)]
    [(x86:vpbroadcastb imm8) (max-unique-inputs imm8)]
    [(x86:vpbroadcastb_128 imm8) (max-unique-inputs imm8)]
    [(x86:vpbroadcastd imm32) (max-unique-inputs imm32)]
    [(x86:vpbroadcastd_128 imm32) (max-unique-inputs imm32)]
    [(x86:vpbroadcastq imm64) (max-unique-inputs imm64)]
    [(x86:vpbroadcastq_128 imm64) (max-unique-inputs imm64)]
    [(x86:vpbroadcastw imm16) (max-unique-inputs imm16)]
    [(x86:vpbroadcastw_128 imm16) (max-unique-inputs imm16)]
    [(x86:vpcmpeqb a b)(+)]
    [(x86:vpcmpeqd a b)(+)]
    [(x86:vpcmpeqq a b)(+)]
    [(x86:vpcmpeqw a b)(+)]
    [(x86:vpcmpgtb a b)(+)]
    [(x86:vpcmpgtd a b)(+)]
    [(x86:vpcmpgtq a b)(+)]
    [(x86:vpcmpgtw a b)(+)]
    [(x86:vperm2f128 a b imm8)(+)]
    [(x86:vperm2i128 a b imm8)(+)]
    [(x86:vpermd a b)(+)]
    [(x86:vpermq a imm8)(+)]
    [(x86:vphaddd a b)(+)]
    [(x86:vphaddsw a b)(+)]
    [(x86:vphaddw a b)(+)]
    [(x86:vphsubd a b)(+)]
    [(x86:vphsubsw a b)(+)]
    [(x86:vphsubw a b)(+)]
    [(x86:vpmaddubsw a b)(+)]
    [(x86:vpmaddwd a b)(+)]
    [(x86:vpmaxsb a b)(+)]
    [(x86:vpmaxsd a b)(+)]
    [(x86:vpmaxsw a b)(+)]
    [(x86:vpmaxub a b)(+)]
    [(x86:vpmaxud a b)(+)]
    [(x86:vpmaxuw a b)(+)]
    [(x86:vpminsb a b)(+)]
    [(x86:vpminsd a b)(+)]
    [(x86:vpminsw a b)(+)]
    [(x86:vpminub a b)(+)]
    [(x86:vpminud a b)(+)]
    [(x86:vpminuw a b)(+)]
    [(x86:vpmovsxbd a) (max-unique-inputs a)]
    [(x86:vpmovsxbq a) (max-unique-inputs a)]
    [(x86:vpmovsxbw a) (max-unique-inputs a)]
    [(x86:vpmovsxdq a) (max-unique-inputs a)]
    [(x86:vpmovsxwd a) (max-unique-inputs a)]
    [(x86:vpmovsxwq a) (max-unique-inputs a)]
    [(x86:vpmovzxbd a) (max-unique-inputs a)]
    [(x86:vpmovzxbq a) (max-unique-inputs a)]
    [(x86:vpmovzxbw a) (max-unique-inputs a)]
    [(x86:vpmovzxdq a) (max-unique-inputs a)]
    [(x86:vpmovzxwd a) (max-unique-inputs a)]
    [(x86:vpmovzxwq a) (max-unique-inputs a)]
    [(x86:vpmuldq a b)(+)]
    [(x86:vpmulhrsw a b)(+)]
    [(x86:vpmulhuw a b)(+)]
    [(x86:vpmulhw a b)(+)]
    [(x86:vpmulld a b)(+)]
    [(x86:vpmullw a b)(+)]
    [(x86:vpmuludq a b)(+)]
    [(x86:vpor a b)(+)]
    [(x86:vpsadbw a b)(+)]
    [(x86:vpshufb a b)(+)]
    [(x86:vpshufd a imm8)(+)]
    [(x86:vpshufhw a imm8)(+)]
    [(x86:vpshuflw a imm8)(+)]
    [(x86:vpsignb a b)(+)]
    [(x86:vpsignd a b)(+)]
    [(x86:vpsignw a b)(+)]
    [(x86:vpslld a imm8)(+)]
    [(x86:vpslldq a imm8)(+)]
    [(x86:vpsllq a imm8)(+)]
    [(x86:vpsllvd a b)(+)]
    [(x86:vpsllvq a b)(+)]
    [(x86:vpsllw a imm8)(+)]
    [(x86:vpsrad a imm8)(+)]
    [(x86:vpsravd a b)(+)]
    [(x86:vpsraw a imm8)(+)]
    [(x86:vpsrld a imm8)(+)]
    [(x86:vpsrldq a imm8)(+)]
    [(x86:vpsrlq a imm8)(+)]
    [(x86:vpsrlvd a b)(+)]
    [(x86:vpsrlvq a b)(+)]
    [(x86:vpsrlw a imm8)(+)]
    [(x86:vpsubb a b)(+)]
    [(x86:vpsubd a b)(+)]
    [(x86:vpsubq a b)(+)]
    [(x86:vpsubsb a b)(+)]
    [(x86:vpsubsw a b)(+)]
    [(x86:vpsubusb a b)(+)]
    [(x86:vpsubusw a b)(+)]
    [(x86:vpsubw a b)(+)]
    [(x86:vpunpckhbw a b)(+)]
    [(x86:vpunpckhdq a b)(+)]
    [(x86:vpunpckhqdq a b)(+)]
    [(x86:vpunpckhwd a b)(+)]
    [(x86:vpunpcklbw a b)(+)]
    [(x86:vpunpckldq a b)(+)]
    [(x86:vpunpcklqdq a b)(+)]
    [(x86:vpunpcklwd a b)(+)]
    [(x86:vpxor a b)(+)]

;; Handle scalars.
    [_ (cond
        [(eq? 'uint8 expr) 0]
        [(eq? 'uint8 expr) 0]
        [(eq? 'int8 expr) 0]
        [(eq? 'uint16 expr) 0]
        [(eq? 'int16 expr) 0]
        [(eq? 'uint32 expr) 0]
        [(eq? 'int32 expr) 0]
        [(eq? 'uint64 expr) 0]
        [(eq? 'int64 expr) 0]
        [else (error (format "x86:max-unique-inputs failed to recognize ~a" expr))])]))

