#lang rosette/safe

(require
  (only-in racket/base error)
  rosette/lib/destruct
  rosette/lib/angelic
  rake/arm/ast/types)

(provide (prefix-out arm: (all-defined-out)))

(define (max-unique-inputs expr)
  (destruct expr

    [(arm:??load _ _ _ _ _) 1]
    [(arm:??shuffle _ _ _) 1]
    [(arm:??swizzle _ _ _ _) 1]
    [(arm:reinterpret Vn) (max-unique-inputs Vn)]

    [(arm:abs Vn) (max-unique-inputs Vn)]
    [(arm:add Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:addhn Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:addp Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:addv Vn) (max-unique-inputs Vn)]
    [(arm:dup Vn) (max-unique-inputs Vn)]
    [(arm:dupn Vn) (max-unique-inputs Vn)]
    [(arm:dupw Vn) (max-unique-inputs Vn)]
    [(arm:ext16i1 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext16i10 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext16i11 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext16i12 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext16i13 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext16i14 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext16i15 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext16i2 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext16i3 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext16i4 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext16i5 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext16i6 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext16i7 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext16i8 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext16i9 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext8i1 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext8i2 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext8i3 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext8i4 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext8i5 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext8i6 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ext8i7 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:mla-vs Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:mla-vv Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:mls-vs Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:mls-vv Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:mul-vs Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:mul-vv Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:neg Vn) (max-unique-inputs Vn)]
    [(arm:raddhn Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:rshrn Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:rsubhn Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:saba Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sabal Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sabd Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sadalp Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:saddl Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:saddlp Vn) (max-unique-inputs Vn)]
    [(arm:saddlv Vn) (max-unique-inputs Vn)]
    [(arm:saddw Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sdot.v2i32.v8i4 Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sdot.v2i32.v8i8 Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sdot.v4i32.v16i4 Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sdot.v4i32.v16i8 Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:shadd Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:shl Vn) (max-unique-inputs Vn)]
    [(arm:shll Vn) (max-unique-inputs Vn)]
    [(arm:shrn Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:shsub Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:smax Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:smaxp Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:smaxv Vn) (max-unique-inputs Vn)]
    [(arm:smin Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sminp Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sminv Vn) (max-unique-inputs Vn)]
    [(arm:smlal-vs Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:smlal-vv Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:smlsl-vs Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:smlsl-vv Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:smull-vs Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:smull-vv Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sqabs Vn) (max-unique-inputs Vn)]
    [(arm:sqadd Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sqdmulh Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sqdmull-vs Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sqdmull-vv Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sqneg Vn) (max-unique-inputs Vn)]
    [(arm:sqrdmulh Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sqrshl Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sqrshrn Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sqrshrun Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sqshl Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sqshlu Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sqshrn Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sqshrun Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sqsub Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sqxtn Vn) (max-unique-inputs Vn)]
    [(arm:sqxtun Vn) (max-unique-inputs Vn)]
    [(arm:srhadd Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:srhsub Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:srshl Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sshl Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sshll Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ssubl Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ssubw Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sub Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:subhn Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:suqadd Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:sxtl Vn) (max-unique-inputs Vn)]
    [(arm:trn1 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:trn2 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:uabd Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:uadalp Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:uaddl Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:uaddlp Vn) (max-unique-inputs Vn)]
    [(arm:uaddlv Vn) (max-unique-inputs Vn)]
    [(arm:uaddw Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:udot.v2i32.v8i4 Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:udot.v2i32.v8i8 Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:udot.v4i32.v16i4 Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:udot.v4i32.v16i8 Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:uhadd Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:uhsub Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:umax Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:umaxp Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:umaxv Vn) (max-unique-inputs Vn)]
    [(arm:umin Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:uminp Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:uminv Vn) (max-unique-inputs Vn)]
    [(arm:umlal-vs Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:umlal-vv Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:umlsl-vs Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:umlsl-vv Vd Vn Vm) (+ (max-unique-inputs Vd) (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:umull-vs Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:umull-vv Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:uqadd Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:uqrshl Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:uqrshrn Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:uqshl Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:uqshrn Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:uqsub Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:uqxtn Vn) (max-unique-inputs Vn)]
    [(arm:urhadd Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:urhsub Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:urshl Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ushl Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:ushll Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:usqadd Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:usubl Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:usubw Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:uxtl Vn) (max-unique-inputs Vn)]
    [(arm:uzip1 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:uzip2 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:vabdl_i16x4 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:vabdl_i32x2 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:vabdl_i8x8 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:vabdl_u16x4 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:vabdl_u32x2 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:vabdl_u8x8 Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]
    [(arm:xtn Vn) (max-unique-inputs Vn)]
    [(arm:zip Vn Vm) (+ (max-unique-inputs Vn) (max-unique-inputs Vm))]


    [_ (cond
        ;; TODO: What if the scalar was the result of a reduction?
        [(eq? 'uint8 expr) 0]
        [(eq? 'int8 expr) 0]
        [(eq? 'uint16 expr) 0]
        [(eq? 'int16 expr) 0]
        [(eq? 'uint32 expr) 0]
        [(eq? 'int32 expr) 0]
        [(eq? 'uint64 expr) 0]
        [(eq? 'int64 expr) 0]
        [else (error (format "max-unique-inputs failed to recognize ~a" expr))])]))
